[directory]
truncation_length = 0

[username]
format = '[$user]($style) '

[hostname]
ssh_symbol = ''
format = '[@$ssh_symbol$hostname]($style) '

[git_branch]
format = ' [$symbol$branch(:$remote_branch)]($style)'

[git_status]
format = '([$all_status$ahead_behind]($style) )'
modified = '*'

[battery]
full_symbol = "‚Ä¢ "
charging_symbol = "‚á° "
discharging_symbol = "‚á£ "
unknown_symbol = "‚ùì "
empty_symbol = "‚ùó "

[cmd_duration]
format = '[$duration]($style) '

[erlang]
symbol = "‚ìî "

[nodejs]
symbol = "[‚¨¢](bold green) "

[pulumi]
symbol = "üßä "

[php]
disabled = true
